#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
KEY=$(cat $SCRIPT_DIR/air-raid.key)

ALERT=$(curl -s "https://api.alerts.in.ua/v1/alerts/active.json?token=$KEY" | jq '.alerts[] | select(.location_title == "Одеська область")')

if [[ $? -ne 0 ]]; then
  echo "Failed to parse"
elif [[ -n "$ALERT" ]]; then
  echo "Air alert"
else
  echo ""
fi
